luna:
  ten:
    # 腾讯地图api
    mapKey: xxx
    # 腾讯api
    secretId: xxx
    secretKey: xxx
    # 腾讯市场api
    skyEyeSecretid: xxx
    skyEyeSecretkey: xxx

  #微信支付信息配置
  wechat:
    # 应用ID
    appId: xxx
    # 公钥
    partner: xxx
    # 私钥
    partnerKey: xxx
    # 异步通知URL
    notifyUrl: xxx

mq:
  pay:
    exchange: exchange.order
    queue: queue.order
    routing: queue.order